name: LeetCode Synchronizer

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6" # Runs automatically every Saturday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run LeetCode Synchronizer
        uses: javaarchive/LeetCode-Synchronizer@master
        with:
          GITHUB_TOKEN: ${{ github.token }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
